services:
  - type: web
    name: personal-finance-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
    autoDeploy: true
    branch: main
    rootDir: backend
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput 