# Generated by Django 5.2.3 on 2025-08-10 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('NEED_TO_GIVE', 'Need to Give'), ('NEED_TO_GET', 'Need to Get')], max_length=15)),
                ('date_created', models.DateField(help_text='When debt was incurred')),
                ('due_date', models.DateField(help_text='Expected payment/return date')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, help_text='Phone number or email', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_date', models.DateTimeField(blank=True, help_text='When marked as paid', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Transaction',
                'verbose_name_plural': 'Debt Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
